<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['intrusion_prevention_app_description'] = 'Приложение "Предотвращения вторжений" активно отслеживает сетевой трафик и блокирует нежелательный трафик, прежде чем он может нанести вред вашей сети.';
$lang['intrusion_prevention_app_name'] = 'Предотвращение вторжений';
$lang['intrusion_prevention_block_time'] = 'Время блокировки';
$lang['intrusion_prevention_blocked_list'] = 'Список заблокированных';
$lang['intrusion_prevention_checksum_invalid'] = 'Контрольная сумма - инвалид.';
$lang['intrusion_prevention_security_id'] = 'Безопасный ID';
$lang['intrusion_prevention_white_list'] = 'Белый список';
