<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['intrusion_prevention_app_description'] = 'The Intrusion Prevention System actively monitors network traffic and blocks unwanted traffic before it can harm your network.';
$lang['intrusion_prevention_app_name'] = 'Intrusion Prevention System';
$lang['intrusion_prevention_block_time'] = 'Время блокировки';
$lang['intrusion_prevention_blocked_list'] = 'Список заблокированных';
$lang['intrusion_prevention_checksum_invalid'] = 'Контрольная сумма - инвалид.';
$lang['intrusion_prevention_security_id'] = 'Безопасный ID';
$lang['intrusion_prevention_white_list'] = 'Белый список';
