#!/bin/sh

# Set default start/boot
#-----------------------

logger -p local6.notice -t installer "app-intrusion-prevention-core - enabling intrusion prevention server"
chkconfig snortsam on

logger -p local6.notice -t installer "app-intrusion-prevention-core - starting intrusion prevention server"
service snortsam start
