<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['intrusion_prevention_app_description'] = 'The Intrusion Prevention System actively monitors network traffic and blocks unwanted traffic before it can harm your network.';
$lang['intrusion_prevention_app_name'] = 'Intrusion Prevention System';
$lang['intrusion_prevention_block_time'] = 'Block Time';
$lang['intrusion_prevention_blocked_list'] = 'Blocked List';
$lang['intrusion_prevention_checksum_invalid'] = 'Checksum is invalid.';
$lang['intrusion_prevention_security_id'] = 'Security ID';
$lang['intrusion_prevention_white_list'] = 'White List';
